jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files for debug
        run: |
          echo "DEBUG:"
          ls -la ./
          echo $JOB_BRANCH_NAME
          echo $JOB_ENV_NAME
          echo ${{ vars.VPC_DEV }}
          echo ${{ vars.VPC_TEST }}
          echo ${{ vars.VPC_STAGE }}
          echo $CF_VPC_DEV
          echo "VPC NOW: $CF_VPC_DEPLOY"
          echo "VPC NOW: ${CF_VPC_DEPLOY@U}"
  
  deploy_python_code_cepfm:
    if: ${{ github.event.inputs.DEPLOY_COMMON_LAMBDA == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Python code - cepfm
        run: |
          pwd
          echo $JOB_BRANCH_NAME
          echo $JOB_ENV_NAME
          echo $CF_VPC_DEV
          echo "DEPLOY_COMMON_LAMBDA"
  
  deploy_python_code_fielddatamgmt:
    if: ${{ github.event.inputs.DEPLOY_COMMON_LAMBDA == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Python code - fielddatamgmt
        run: |
          pwd
          echo "DEPLOY_COMMON_LAMBDA"

  docker_preparation_di:
    if: ${{ github.event.inputs.DEPLOY_STACK_DI == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker preparation - DI
        run: |
          pwd
          echo "DEPLOY_STACK_DI"

  docker_preparation_importimplement:
    if: ${{ github.event.inputs.DEPLOY_STACK_IMPORTIMPLEMENT == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker preparation - ImportImplement
        run: |
          pwd
          echo "DEBUG: Original Dockerfile"
          echo "DEPLOY_STACK_IMPORTIMPLEMENT"
