name: diff-tasks-with-checkbox

on:
  workflow_dispatch:
    inputs:
      deploy_common_lambda:
        description: 'Deploy COMMON LAMBDA?'
        required: true
        default: false
        type: boolean
      deploy_stack_di:
        description: 'Deploy STACK DI?'
        required: true
        default: false
        type: boolean
      deploy_stack_importimplement:
        description: 'Deploy STACK IMPORTIMPLEMENT?'
        required: true
        default: false
        type: boolean

jobs:
  conditional_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Deploy COMMON LAMBDA"
        if: ${{ github.event.inputs.deploy_common_lambda == 'true' }}
        run: echo "Running deployment for COMMON LAMBDA"

      - name: "Deploy STACK DI"
        if: ${{ github.event.inputs.deploy_stack_di == 'true' }}
        run: echo "Running deployment for STACK DI"

      - name: "Deploy STACK IMPORTIMPLEMENT"
        if: ${{ github.event.inputs.deploy_stack_importimplement == 'true' }}
        run: echo "Running deployment for STACK IMPORTIMPLEMENT"
