name: Manual Pipeline with Multiple Boolean Options

on:
  workflow_dispatch:
    inputs:
      run_cat:
        description: 'Run cat operation?'
        required: true
        default: false
        type: boolean
      run_dog:
        description: 'Run dog operation?'
        required: true
        default: false
        type: boolean
      run_bird:
        description: 'Run bird operation?'
        required: true
        default: false
        type: boolean

jobs:
  conditional_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Operation: Cat"
        if: ${{ github.event.inputs.run_cat == 'true' }}
        run: echo "Running tasks for 'cat' operation"

      - name: "Operation: Dog"
        if: ${{ github.event.inputs.run_dog == 'true' }}
        run: echo "Running tasks for 'dog' operation"

      - name: "Operation: Bird"
        if: ${{ github.event.inputs.run_bird == 'true' }}
        run: echo "Running tasks for 'bird' operation"
