name: Deploy via SSH

on:
  workflow_dispatch:
    inputs:
      documentroots:
        description: "Comma-separated list of DOCUMENTROOT values (e.g., 'root1,root2'). Use 'all' to select all."
        required: true
        default: "all"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Define DOCUMENTROOT values
        id: define-values
        run: |
          # List of all possible DOCUMENTROOT values
          ALL_DOCUMENTROOTS=("root1" "root2" "root3" "root4") # Add all 70 values here

          # Read input
          INPUT="${{ github.event.inputs.documentroots }}"

          # Process input
          if [[ "$INPUT" == "all" ]]; then
            SELECTED_DOCUMENTROOTS=("${ALL_DOCUMENTROOTS[@]}")
          else
            IFS=',' read -ra SELECTED_DOCUMENTROOTS <<< "$INPUT"
          fi

          # Export the list as a single string for use in other steps
          echo "SELECTED=$(IFS=,; echo "${SELECTED_DOCUMENTROOTS[*]}")"
          echo "SELECTED_DOCUMENTROOTS=$SELECTED" >> $GITHUB_ENV

      - name: Run SSH Command
        env:
          DOCUMENTROOTS: ${{ env.SELECTED_DOCUMENTROOTS }}
        run: |
          echo "Selected DOCUMENTROOTS: $DOCUMENTROOTS"

          # Construct and execute your SSH command
          #ssh user@host "some-command --documentroots \"$DOCUMENTROOTS\""
