name: Deploy via SSH

on:
  workflow_dispatch:
    inputs:
      documentroots:
        description: "Select DOCUMENTROOT(s) from the predefined list (comma-separated if multiple)"
        required: true
        default: "all"
        options: # Predefined list of valid DOCUMENTROOT values
          - all
          - root1
          - root2
          - root3
          - root4
          # Add more values as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Process Selected DOCUMENTROOT Values
        id: process-roots
        run: |
          # List of all possible DOCUMENTROOT values
          ALL_DOCUMENTROOTS=("root1" "root2" "root3" "root4") # Add the full list

          # Input from the workflow_dispatch
          INPUT="${{ github.event.inputs.documentroots }}"

          if [[ "$INPUT" == "all" ]]; then
            SELECTED_DOCUMENTROOTS=("${ALL_DOCUMENTROOTS[@]}")
          else
            IFS=',' read -ra INPUT_ARRAY <<< "$INPUT"
            SELECTED_DOCUMENTROOTS=()
            for item in "${INPUT_ARRAY[@]}"; do
              # Validate the input against the predefined list
              if [[ " ${ALL_DOCUMENTROOTS[*]} " =~ " $item " ]]; then
                SELECTED_DOCUMENTROOTS+=("$item")
              else
                echo "Invalid DOCUMENTROOT: $item"
                exit 1
              fi
            done
          fi

          # Export the selected DOCUMENTROOTS as a comma-separated string
          echo "SELECTED=$(IFS=,; echo "${SELECTED_DOCUMENTROOTS[*]}")"
          echo "SELECTED_DOCUMENTROOTS=$SELECTED" >> $GITHUB_ENV

      - name: Run SSH Command
        env:
          DOCUMENTROOTS: ${{ env.SELECTED_DOCUMENTROOTS }}
        run: |
          echo "Selected DOCUMENTROOTS: $DOCUMENTROOTS"

          # Construct and execute your SSH command
          echo \"$DOCUMENTROOTS\""

