name: Manual Pipeline
on:
  workflow_dispatch:
    inputs:
      operation:
        description: 'Choose the operation to perform'
        required: true
        default: 'cat'
        type: string
        options:
          - cat
          - dog
jobs:
  conditional_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Task for 'cat' operation
      - name: "Operation: Cat"
        if: ${{ github.event.inputs.operation == 'cat' }}
        run: echo "Running tasks for 'cat' operation"

      # Task for 'dog' operation
      - name: "Operation: Dog"
        if: ${{ github.event.inputs.operation == 'dog' }}
        run: echo "Running tasks for 'dog' operation"

      # Task for 'bird' operation
      - name: "Operation: Bird"
        if: ${{ github.event.inputs.operation == 'bird' }}
        run: echo "Running tasks for 'bird' operation"

