name: deploy-nonprod

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment (dev, test, stage)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - stage
      DEPLOY_COMMON_LAMBDA:
        description: 'Deploy COMMON LAMBDA?'
        required: true
        default: false
        type: boolean
      DEPLOY_STACK_DI:
        description: 'Deploy STACK DI?'
        required: true
        default: false
        type: boolean
      DEPLOY_STACK_IMPORTIMPLEMENT:
        description: 'Deploy STACK IMPORTIMPLEMENT?'
        required: true
        default: false
        type: boolean

jobs:
  deploy:
    uses: ./actions-yaml/cep-ods.yaml
    with:
      environment: ${{ github.event.inputs.environment }}
      DEPLOY_COMMON_LAMBDA: ${{ github.event.inputs.DEPLOY_COMMON_LAMBDA }}
      DEPLOY_STACK_DI: ${{ github.event.inputs.DEPLOY_STACK_DI }}
      DEPLOY_STACK_IMPORTIMPLEMENT: ${{ github.event.inputs.DEPLOY_STACK_IMPORTIMPLEMENT }}
    secrets:
      VSTS_CREDENTIALS_ID: ${{ secrets.VSTS_CREDENTIALS_ID }}
